
call lcmccb.p_kwee.pcm_kvee_notmkd(&pdat, &pleskgesk, &pdb_lesk, &pnot_empty);

select  upper(a.addressshort) addressshort,
        DBM_NAME,
        '' " ",
        Company,
        Inn,
        AccountNum,
        BankName,
        AccountNumOff,
        Bik,
        Month,
        Period,
        Date1,
        Date2,
        Phone,
        Email,
        OrgAddress,
        Barcode,
        Ls,
        Fio,
        Address,
        Count,
        Dpokaz,
        Npokaz,
        Srasch,
        FSumType,
        Dolg,
        Oplata,
        OldPokaz1,
        OldPokaz2,
        OldPokaz3,
        OldPokaz4,
        Pokaz1,
        Pokaz2,
        Pokaz3,
        Pokaz4,
        KoefTr1,
        KoefTr2,
        KoefTr3,
        KoefTr4,
        Kwt1,
        Kwt2,
        Kwt3,
        Kwt4,
        Tarif1,
        Tarif2,
        Tarif3,
        Tarif4,
        Sum1,
        Sum2,
        Sum3,
        Sum4,
        Sum,
        to_char(round(lcmccb.fcm_to_number(RKwt1), 2)) RKwt1,
        to_char(round(lcmccb.fcm_to_number(RKwt2), 2)) RKwt2,
        to_char(round(lcmccb.fcm_to_number(RKwt3), 2)) RKwt3,
        to_char(round(lcmccb.fcm_to_number(RKwt4), 2)) RKwt4,
        to_char(round(lcmccb.fcm_to_number(RKwt), 2)) RKwt,
        RSum1,
        RSum2,
        RSum3,
        RSum4,
        Rsum,
        Total1,
        Total2,
        Total3,
        Total4,
        Total,
        DebtInTitle,
        DebtIn,
        TotalPay,
        PrePay,
        DebtIn1,
        DebtIn2,
        DebtIn3,
        DebtIn4,
        DebtIn5,
        DebtLaw1,
        DebtLaw2,
        DebtLaw3,
        DebtLaw,
        Service1,
        Service2,
        Service3,
        Service,
        CTarifTitle,
        CTarifDate1,
        CTarifDate2,
        VTarifDate1,
        VTarifDate2,
        CTarif1,
        CTarif2,
        VTarif1,
        VTarif2,
        DCTarif1,
        DCTarif2,
        NCTarif1,
        NCTarif2,
        DVTarif1,
        DVTarif2,
        NVTarif1,
        NVTarif2,
        FInfo1,
        Info1,
        Info2,
        FInfo3,
        Info3,
        rownum KolKv,
        PayType,
        Npuch,
        KolKom,
        TINF,
        DATEPOKAZ,
        OZPU,
        CDAY,
        CNIGHT,
        DOLZHNIK
   from (select *
           from lcmccb.CM_KVEE_NOTMKD_CSV k 
          where leskgesk = &pleskgesk
            and pdat = &pdat
            and bd_lesk = case &the_filter_is_using
                            when 'true' then
                              bd_lesk
                            else
                              &pdb_lesk
                          end
          order by upper(k.addressshort),
                   upper(k.address3),
                   to_number(regexp_replace(k.address2,'[^[[:digit:]]]*')),
                   upper(k.address2),
                   to_number(regexp_replace(k.address4,'[^[[:digit:]]]*')),
                   upper(k.address4)) a
          where exists (select * from rusadm.ci_acct_char ac, 
                                      leskdata.&filter ldb
                        where ac.char_type_cd = 'LKKLOGIN' 
                        and a.ls = ac.adhoc_char_val 
                        and ldb.acct_id = ac.acct_id);